[project]
name = "flashbots"
version = "3.0.0"
description = "Web3.py plugin for using Flashbots' bundle APIs"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [
    { name = "Georgios Konstantopoulos", email = "me@gakonst.com" },
    { name = "Nikolas Papaioannou", email = "n0k0@hacky.software" },
    { name = "Brock Smedley", email = "brock@flashbots.net" },
]
dependencies = [
    "web3>=7.0.0",
    "urllib3<2.0",
    "websockets>=13.0.0,<14.0.0",
    "eth-account>=0.13.7",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "ruff>=0.5.4",
    "pytest-recording>=0.11.0",
    "vcrpy>=4.1.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
target-version = "py312"

[tool.hatch.build.targets.wheel]
packages = ["flashbots"]
